
CREATE TABLE BITACORA_EVENTOS (
	ID INT IDENTITY (1,1),
	NOMBRE_EVENTO VARCHAR(30),
	DESCRIPCION VARCHAR(200),
	TABLA VARCHAR(30),
	FECHA_EVENTO DATETIME,
	DATOS_POSTERIORES VARCHAR(MAX),
	DATOS_ANTERIORES VARCHAR(MAX)
)
