USE master;
GO

create database BD_REPLICADA
go
USE master;
GO

ALTER DATABASE BD_REPLICADA
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

RESTORE FILELISTONLY
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER26\MSSQL\Backup\backupCopia.bak';
go


RESTORE DATABASE BD_REPLICADA
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER26\MSSQL\Backup\backupCopia.bak'
WITH
    MOVE 'ADMINISTRACION_BASE_DATOS'
        TO 'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER26\MSSQL\DATA\BD_REPLICADA.mdf',

    MOVE 'ADMINISTRACION_BASE_DATOS_log'
        TO 'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER26\MSSQL\DATA\BD_REPLICADA_log.ldf',

    REPLACE;
GO

ALTER DATABASE BD_REPLICADA
SET MULTI_USER;
GO